//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoologicoSite
{
    using System;
    using System.Collections.Generic;
    
    public partial class T_Animal
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public T_Animal()
        {
            this.T_Zoo = new HashSet<T_Zoo>();
        }
    
        public int ID { get; set; }
        public string Sexo { get; set; }
        public Nullable<System.DateTime> Nacimiento { get; set; }
        public Nullable<int> ID_Pais { get; set; }
        public int ID_Especie { get; set; }
        public string Nombre_Animal { get; set; }
    
        public virtual T_Especie T_Especie { get; set; }
        public virtual T_Pais T_Pais { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<T_Zoo> T_Zoo { get; set; }
    }
}
