//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ZoologicoSite
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class ZOOSEntities : DbContext
    {
        public ZOOSEntities()
            : base("name=ZOOSEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<T_Users> T_Users { get; set; }
        public virtual DbSet<T_Animal> T_Animal { get; set; }
        public virtual DbSet<T_Especie> T_Especie { get; set; }
        public virtual DbSet<T_Familia> T_Familia { get; set; }
        public virtual DbSet<T_Ciudades> T_Ciudades { get; set; }
        public virtual DbSet<T_Continente> T_Continente { get; set; }
        public virtual DbSet<T_Pais> T_Pais { get; set; }
        public virtual DbSet<T_Zoo> T_Zoo { get; set; }
    }
}
